### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by barrywe7** [vanshg/KrazyKotlin#1]
The extension in date to return a calendar object looks quite complicated.

```
var Date.calendar: Calendar
    get() = Calendar.getInstance().apply { time = this@calendar }
    set(value) {
        time = value.timeInMillis
    }
```

Isn't that the equivalent of this?

```
val Date.calendar: Calendar
    get() = Calendar.getInstance().apply { timeInMillis = this@calendar.time }
```

**Comment by vanshg** [comment]
Nope it wouldn't be -- your proposed change is a `val` instead of `var`, therefore it doesn't have a setter and would not be able to be reassigned (aka, setting a new `Calendar` on the `Date`)
